---
title: "Cluster size analysis"
output: html_notebook
---


```{r}
library(Seurat)
library(tidyverse)
source("~/multiOmic_benchmark/KNN_agreement.R")

outdir <- "~/multiOmic_benchmark/report/output/20191113_clusterSize_PBMC/"
ifelse(!dir.exists(outdir), dir.create(outdir), FALSE)
```

```{r}
pred.labels <- readRDS("~/models/clusterSize_labelTransfer_PBMC.RDS")
annotation_list <- readRDS("~/models/clusterSize_trueAnnotations_PBMC.RDS")
resolutions <- seq(0.5,1.5, by = 0.1)
pred.labels
```
```{r}
## Load original data
orig.ATAC <- readRDS("~/my_data/10X_data/atac_pbmc_10k_nextgem.snapATAC.RDS")
sce.list <- readRDS("~/my_data/10X_data/PBMC_SCElist_20191105.RDS")
orig.RNA <- sce.list$RNA

## Make SeuratObjects
atac.seu <- snapToSeurat(
    obj=orig.ATAC, 
    eigs.dims=1:20, 
    norm=TRUE,
    scale=TRUE
    )
atac.seu <- RenameCells(atac.seu, new.names = orig.ATAC@metaData$barcode)
atac.seu <- RunUMAP(atac.seu, reduction = "SnapATAC", reduction.name = "umap.snap", dims=1:20)

```
### Prediction score
```{r, fig.width=15, fig.height=7}
pred.labels %>%
  ggplot(aes(color=res, group=as.factor(res), score)) +
  stat_ecdf() +
  facet_wrap(method~.) +
  scale_color_viridis_c(name="Clustering resolution") +
  theme_bw(base_size = 16) +
  geom_vline(xintercept = 0.5, linetype=2) +
  ylab("ECDF") + xlab("Label prediction score") +
  ggsave(paste0(outdir, "prediction_score.png"), width=10, height = 4)
```

### Cell type composition
```{r}
orig.composition <- 
  map(seq_along(resolutions), ~ data.frame(predicted.id = annotation_list[[.x]], res=resolutions[.x], method="original.RNA")) %>%
  purrr::reduce(bind_rows) %>%
  group_by(res) %>%
  mutate(tot.cells=n()) %>%
  ungroup() %>%
  group_by(res, predicted.id) %>%
  dplyr::mutate(frac=n()/tot.cells)  %>%
  ungroup() 

orig.rank <- 
  orig.composition %>%
  group_by(res) %>%
  dplyr::mutate(orig.rank=dense_rank(frac)) %>%
  select(res, predicted.id, orig.rank) %>% distinct() %>%
  ungroup() 
  
pl.df <- 
  pred.labels %>%
  group_by(res, method) %>%
  mutate(tot.cells=n()) %>%
  ungroup() %>%
  group_by(res, method, predicted.id) %>%
  dplyr::mutate(frac=n()/tot.cells, mean.score=mean(score)) %>%
  ungroup() %>%
  bind_rows(orig.composition) %>%
  left_join(orig.rank, by=c("predicted.id", "res")) %>%
  dplyr::rename(rank=orig.rank) %>%
  dplyr::arrange(rank) %>%
  dplyr::mutate(predicted.id = factor(predicted.id, levels=unique(predicted.id))) %>%
  select(res, mean.score, predicted.id, frac, method) %>%
  distinct()

pl.df %>%
  filter(res==1.5) %>%
  ggplot(aes(predicted.id, frac, fill=mean.score, color=mean.score)) +
  facet_grid(.~method) +
  coord_flip() +
  geom_point() +
  geom_bar(width=0.1, stat="identity")
  
```
```{r, fig.width=10, fig.height=12}
pl.df %>% 
  ggplot(aes(predicted.id, frac, color=method)) +
  geom_point(size=2) + 
  facet_grid(res~.) +
  scale_color_brewer(palette = "Set1")
```
```{r}
orig.composition %>%
  group_by(res) %>%
  distinct(predicted.id) %>%
  summarise(n_clusters=n())
cor.conos <- pl.df %>%
  filter(method=="conos") %>%
  left_join(filter(pl.df, method=="original.RNA"), by=c("res", 'predicted.id')) %>%
  group_by(res, method.x) %>%
  summarise(cor = cor(frac.x, frac.y, method = "pearson"))
cor.cca <- pl.df %>%
  filter(method=="CCA") %>%
  left_join(filter(pl.df, method=="original.RNA"), by=c("res", 'predicted.id')) %>%
  group_by(res, method.x) %>%
  summarise(cor = cor(frac.x, frac.y, method = "pearson"))
cor.liger <- pl.df %>%
  filter(method=="liger") %>%
  left_join(filter(pl.df, method=="original.RNA"), by=c("res", 'predicted.id')) %>%
  group_by(res, method.x) %>%
  summarise(cor = cor(frac.x, frac.y, method = "pearson"))

bind_rows(cor.cca, cor.liger, cor.conos) %>%
  ggplot(aes(res, cor)) +
  geom_point(aes(color=method.x), size=2) +
  scale_color_brewer(palette = "Set1")

```

### KNN score
```{r}
k = 30

atac.seu <- FindNeighbors(atac.seu, assay = "ATAC", reduction = "SnapATAC", dims = 1:15, k.param = k)
atac.nn.list <- getNNlist(atac.seu)

# atac.nn.list
# pred.label.df <- dplyr::filter(pred.labels, method=="CCA" & res==0.5) %>%
#   column_to_rownames("cell")
# 
# KNN_score <- function(atac.nn.list, pred.label.df){
#   knn.score <- imap_dbl(atac.nn.list, ~ sum(pred.label.df[.x, 'predicted.id'] == pred.label.df[.y, 'predicted.id'])/k)         
#   data.frame(knn.score) %>% rownames_to_column("cell")
#   }
# 
# knn_score_df <- pred.labels %>%
#   split(list(.$method, .$res)) %>%
#   map(~ rownames_to_column(.x) %>% column_to_rownames("cell")) %>%
#   # .[1:3] %>%
#   map( ~ mutate(KNN_score(atac.nn.list, .), res=.$res[1], method=.$method[1])) %>%
#   purrr::reduce(bind_rows)
# 
# knn_score_random <-
#   pred.labels %>%
#   split(list(.$method, .$res)) %>%
#   map(~ rownames_to_column(.x) %>% column_to_rownames("cell")) %>%
#   map( ~ mutate(.x, predicted.id=sample(predicted.id))) %>%
#   # .[1:3] %>%
#   map( ~ mutate(KNN_score(atac.nn.list, .), res=.$res[1], method=.$method[1])) %>%
#   purrr::reduce(bind_rows)

knn.test.pred <- pred.labels %>%
  split(list(.$method, .$res)) %>%
  map(~ setNames(.x$predicted.id, .x$cell)) %>%
  map( ~ test.knn(atac.nn.list, .x))

imap(knn.test.pred, ~ data.frame(D=.x$D, method=.y)) %>%
  purrr::reduce(bind_rows) %>%
  mutate(method=str_replace(method, "\\.", "_")) %>%
  tidyr::separate("method", c("method", "res"), sep='_') %>%
  ggplot(aes(res, D)) +
  geom_point(aes(color=method), size=2) +
  geom_line(aes(group=method, color=method)) +
  scale_color_brewer(palette = "Set1") +
  theme_bw(base_size = 16) +
  xlab("Clustering resolution") + ylab("KNN score") +
  ggsave(paste0(outdir, "knn_score.png"), width=8, height = 5)

```

```{r, fig.width=15, fig.height=7}
imap(knn.test.pred, ~ data.frame(knn.score=.x$KNN_score, method=.y)) %>%
  purrr::reduce(bind_rows) %>%
  mutate(method=str_replace(method, "\\.", "_")) %>%
  tidyr::separate("method", c("method", "res"), sep='_') %>%
  ggplot(aes(color=as.factor(res), knn.score)) +
  stat_ecdf() +
  facet_wrap(method~.) +
  scale_color_viridis_d() +
  theme_bw(base_size = 16)
```

```{r}
atac.seu <- AddMetaData(atac.seu, metadata = filter(pred.labels, method=="conos" & res==1.5)[,"predicted.id"], col.name = "pred_conos0.5")
atac.seu <- AddMetaData(atac.seu, metadata = filter(pred.labels, method=="CCA" & res==1.5)[,"predicted.id"], col.name = "pred_CCA0.5")

DimPlot(atac.seu, reduction = "umap.snap", group.by="pred_CCA0.5")
DimPlot(atac.seu, reduction = "umap.snap", group.by="pred_conos0.5")
```
```{r}
ix <- 1:1000
x <- as.matrix(atac.seu@reductions$SnapATAC@cell.embeddings)[ix,]
lab <- atac.seu$pred_CCA0.5[ix]
rand_lab <- sample(lab) %>% setNames(., names(lab))

D <- dist((x)) %>% as.matrix()
N_6 <- sum(lab=='6')
N <- length(lab)
k=5

colnames(D)
pheatmap::pheatmap(D, annotation_col = list(label=lab))
knn_list <- map(1:100, ~ FastKNN::k.nearest.neighbors(i=.x, D, k=5))

P_6 <- (N_6/N)^k

P_6
KNN_6 <- map_dbl(knn_list[which(lab==6)], ~ sum(lab[.x] == '6')/k)
KNN_rand <- map_dbl(knn_list[which(lab==6)], ~ sum(rand_lab[.x] == '6')/k)

KNN_6
KNN_rand

pred.lab <- pred.labels %>% dplyr::filter(res==0.8 & method=="CCA")
pred.lab
knn_score_df %>% filter(res==0.8 & method=="CCA") %>%
  left_join(pred.lab) %>%
  group_by(predicted.id) %>%
  mutate(cluster.size=n()) %>%
  ggplot(aes(cluster.size, knn.score)) +
  geom_boxplot(aes(group=cluster.size))
```

